### ISSUE TITLE
Cite `jax-dataloader`

### ISSUE THREAD

**Issue by BirkhoffG** [HMUNACHI/nanodl#11]
Hi @HMUNACHI , 

Your [dataloader code](https://github.com/HMUNACHI/nanodl/blob/97252baa07d675e8a60c229dda696368336e4c42/nanodl/__src/utils/data.py) is heavily referred to the [jax-dataloader repository](https://github.com/BirkhoffG/jax-dataloader/tree/v0.0.5/jax_dataloader), which is totally okay. But could you kindly cite the repository for reference? 

Thank you!

**Comment by HMUNACHI** [comment]
Hi @BirkhoffG, NanoDL's dataloader indeed simplifies jax-dataloader and the repository has been appropriately referenced, was only noted in the readthedocs before. Your project is great btw, I use it so much, check out my FBNET project.
